import datetime as dt
import json
import os
from typing import TypedDict

import yfinance as yf
from langchain_anthropic import ChatAnthropic
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import create_react_agent

from pulse.config import MODEL, REPORTS_DIR, WATCHLIST
from pulse.news import fetch_news, search_news, store_news
from pulse.portfolio import load_portfolio, snapshot
from pulse.prompts import CONTEXT, GEMS_PROMPT, SUMMARIZE_PROMPT
from pulse.screener import screen

RETURN_WINDOWS = {"1d": 1, "5d": 5, "1mo": 21, "3mo": 63}  # trading days


# The shared state every node reads from and writes partial updates to
class ResearchState(TypedDict, total=False):
    market: dict            # index returns + movers
    portfolio: dict         # portfolio.snapshot()
    news: dict              # ticker -> list of article metadata
    candidates: list[dict]  # screen survivors + metrics
    gems_analysis: str      # LLM output
    summary: str            # LLM output: market summary + portfolio review
    report_path: str


def _llm():
    return ChatAnthropic(model=MODEL, max_tokens=4000)


def _tickers() -> list[str]:
    holdings = [h["ticker"] for h in load_portfolio()]
    return sorted(set(WATCHLIST + holdings))


def fetch_market(state: ResearchState) -> dict:
    tickers = _tickers()
    prices = yf.download(["SPY", "QQQ"] + tickers, period="6mo",
                         auto_adjust=True, progress=False)["Close"].ffill()
    indexes = {
        idx: {w: round((prices[idx].iloc[-1] / prices[idx].iloc[-d - 1] - 1) * 100, 2)
              for w, d in RETURN_WINDOWS.items() if len(prices) > d}
        for idx in ("SPY", "QQQ")
    }
    day_pct = (prices[tickers].iloc[-1] / prices[tickers].iloc[-2] - 1) * 100
    movers = [{"ticker": t, "day_pct": round(p, 2)}
              for t, p in day_pct.abs().nlargest(5).items()
              for p in [day_pct[t]]]
    return {"market": {"indexes": indexes, "movers": movers}}


def fetch_news_node(state: ResearchState) -> dict:
    news = {}
    for t in _tickers():
        try:
            articles = fetch_news(t, limit=5)
            store_news(articles)
            news[t] = [{"title": a["title"], "source": a["source"], "url": a["url"]}
                       for a in articles]
        except Exception as e:  # one bad ticker shouldn't kill the pipeline
            print(f"  news for {t} failed: {e}")
    return {"news": news}


def portfolio_node(state: ResearchState) -> dict:
    return {"portfolio": snapshot(load_portfolio())}


def screen_node(state: ResearchState) -> dict:
    return {"candidates": screen()}


def has_candidates(state: ResearchState) -> str:
    return "gems" if state.get("candidates") else "summarize"


def gems_node(state: ResearchState) -> dict:
    gem_news = {c["symbol"]: search_news("growth catalyst earnings", ticker=c["symbol"], k=3)
                for c in state["candidates"]}
    prompt = GEMS_PROMPT.format(
        candidates=json.dumps(state["candidates"], indent=1, default=str),
        news=json.dumps(gem_news, indent=1, default=str),
    )
    return {"gems_analysis": _llm().invoke(prompt).text()}


def summarize_node(state: ResearchState) -> dict:
    prompt = SUMMARIZE_PROMPT.format(
        date=dt.date.today(),
        market=json.dumps(state["market"], indent=1, default=str),
        portfolio=json.dumps(state["portfolio"], indent=1, default=str),
        news=json.dumps(state["news"], indent=1, default=str),
        gems_analysis=state.get("gems_analysis", "(none today)"),
    )
    return {"summary": _llm().invoke(prompt).text()}


def write_report(state: ResearchState) -> dict:
    sources = [f"- [{a['title']}]({a['url']}) — {a['source']}"
               for arts in state["news"].values() for a in arts]
    body = "\n\n".join([
        f"# Pulse Daily Research — {dt.date.today()}",
        state["summary"],
        state.get("gems_analysis", "## Hidden Gems\nNo candidates passed today's screen."),
        "## Sources\n" + ("\n".join(sources) or "None"),
        "*Generated by Pulse. Not financial advice.*",
    ])
    os.makedirs(REPORTS_DIR, exist_ok=True)
    path = os.path.join(REPORTS_DIR, f"{dt.date.today()}.md")
    with open(path, "w") as f:
        f.write(body)
    return {"report_path": path}


def build_report_graph():
    g = StateGraph(ResearchState)
    g.add_node("fetch_market", fetch_market)
    g.add_node("fetch_news", fetch_news_node)
    g.add_node("portfolio", portfolio_node)
    g.add_node("screen", screen_node)
    g.add_node("gems", gems_node)
    g.add_node("summarize", summarize_node)
    g.add_node("write_report", write_report)

    g.add_edge(START, "fetch_market")
    g.add_edge("fetch_market", "fetch_news")
    g.add_edge("fetch_news", "portfolio")
    g.add_edge("portfolio", "screen")
    g.add_conditional_edges("screen", has_candidates, {"gems": "gems", "summarize": "summarize"})
    g.add_edge("gems", "summarize")
    g.add_edge("summarize", "write_report")
    g.add_edge("write_report", END)
    return g.compile()


def build_chat_agent(checkpointer):
    from pulse.tools import ALL_TOOLS
    return create_react_agent(_llm(), tools=ALL_TOOLS, prompt=CONTEXT,
                              checkpointer=checkpointer)
